# Common settings
timezone: Europe/London
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://florentmetz.github.io" # the base hostname & protocol for your site
locale: "en"
# simple flag used to turn comments on or off
disable_comments: false

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Data settings
collections:
  travels:
    output: true
    permalink: /voyages/:slug.html

# SEO settings
title: Flotz Chronicles
description: A bit of everything, from English technical articles about Web Development to French journeys in Nepal
#logo: /todo.png
