# Site settings
title: Flotz Blog
timezone: Europe/London
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://florentmetz.github.io" # the base hostname & protocol for your site

collections:
  travels:
    output: true
    permalink: /voyages-:slug/

# Build settings
markdown: kramdown

highlighter: rouge

gems:
  - jekyll-seo-tag
  - jekyll-feed
